"""empty message

Revision ID: 9dfdaefb8f16
Revises: caf8d1d35540
Create Date: 2019-09-12 22:02:27.664036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9dfdaefb8f16'
down_revision = 'caf8d1d35540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist', 'playlist_system_owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist', sa.Column('playlist_system_owner', mysql.INTEGER(
        display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
