"""empty message

Revision ID: a3adc147c9aa
Revises: 
Create Date: 2019-07-31 14:34:24.607043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3adc147c9aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'playlist', 'user', ['user_system_id'], ['id'])
    op.create_foreign_key(None, 'playlist_like', 'user',
                          ['user_system_id'], ['id'])
    op.create_foreign_key(None, 'playlist_like', 'playlist', [
                          'playlist_system_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'playlist_like', type_='foreignkey')
    op.drop_constraint(None, 'playlist_like', type_='foreignkey')
    op.drop_constraint(None, 'playlist', type_='foreignkey')
    # ### end Alembic commands ###
