"""empty message

Revision ID: caf8d1d35540
Revises: df30bb57d8b8
Create Date: 2019-09-12 20:21:13.230267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'caf8d1d35540'
down_revision = 'df30bb57d8b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playlist', 'user_system_id', new_column_name='playlist_system_owner_id')
    op.add_column('playlist', sa.Column('playlist_spotify_owner_id', sa.String(length=255), nullable=False))
    op.drop_column('playlist', 'playlist_spotify_owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playlist', 'playlist_system_owner', new_column_name='user_system_id')
    op.add_column('playlist', 'playlist_spotify_owner', sa.Boolean, unique=False)
    op.drop_column('playlist', 'playlist_spotify_owner_id')
    # ### end Alembic commands ###
