"""empty message

Revision ID: df30bb57d8b8
Revises: a3adc147c9aa
Create Date: 2019-08-02 13:39:40.454133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df30bb57d8b8'
down_revision = 'a3adc147c9aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist', 'spotify_owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist', sa.Column('spotify_owner', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###
